export const wedding = {
  bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
  bismillahLatin: "In the name of Allah, the Most Gracious, the Most Merciful",
  ayah: "And of His signs is that He created for you mates from among yourselves, that you may find tranquillity in them; and He placed between you affection and mercy.",
  ayahRef: "Surah Ar-Rum 30:21",
  parentsInvite: {
    badge: "Heartfelt Invitation",
    parents: "Mr. Baji Sheik & Mrs. Jareena Sheik",
    message: "Baji and Jareena inviting you for our only son's wedding",
    subtext:
      "With hearts full of gratitude and joy, we request the honour of your presence and warm blessings as our beloved only son begins his journey of marriage.",
  },
  bride: {
    name: "Summaya",
    fullName: "Summaya Ashraf",
    line: "Daughter of Mr. & Mrs. Ashraf",
    blurb: "A radiant soul stepping gracefully into a lifetime of cherished love, faith and companionship.",
    photo: "/wedding/ring-ceremony-2.jpg",
  },
  groom: {
    name: "Anwaruddin",
    fullName: "Anwaruddin Sheik",
    line: "Beloved Only Son of Mr. Baji Sheik & Mrs. Jareena Sheik",
    blurb: "Baji and Jareena inviting you for our only son's wedding.",
    photo: "/wedding/ring-ceremony-1.jpg",
  },
  heroArt: "/wedding/hero.jpg",
  introCover: "/wedding/ChatGPT Image Aug 12, 2026 at 11_08_45 PM.png",
  introVideo: "/wedding/Continuous_wedding_invitation_an…_202608122343.mp4",
  // Primary wedding ceremony time (IST)
  dateISO: "2026-10-01T10:30:00+05:30",
  endISO: "2026-10-01T14:30:00+05:30",
  dateLabel: "Thursday, 1 October 2026",
  timeLabel: "Wedding Ceremony: 10:30 AM",
  venue: {
    name: "Sri Siri Convention",
    address: "Wedding Ceremony Venue",
    mapsUrl: "https://share.google/k6Z1WMeH3PJUarstX",
    preview: "/wedding/map.jpg",
  },
  events: [
    {
      id: "wedding",
      title: "Wedding Ceremony",
      subtitle: "Nikah & Auspicious Muhurtham",
      dateLabel: "Thursday, 1 October 2026",
      timeLabel: "10:30 AM onwards",
      dateISO: "2026-10-01T10:30:00+05:30",
      endISO: "2026-10-01T14:30:00+05:30",
      venueName: "Sri Siri Convention",
      address: "Wedding Ceremony Hall",
      mapsUrl: "https://share.google/k6Z1WMeH3PJUarstX",
      badge: "Main Event",
    },
    {
      id: "reception",
      title: "Wedding Reception & Valima",
      subtitle: "Celebration Dinner & Felicitations",
      dateLabel: "Saturday, 3 October 2026",
      timeLabel: "Evening 7:00 PM onwards",
      dateISO: "2026-10-03T19:00:00+05:30",
      endISO: "2026-10-03T23:00:00+05:30",
      venueName: "Kunaparaju Appalaraju Sitamma Lions Auditorium",
      address: "Reception & Valima Venue",
      mapsUrl: "https://share.google/MxLHfEIza3vKCPShy",
      badge: "Reception",
    },
  ],
  meta: {
    siteUrl: "https://anwaruddin-weds-summaya.invitingyou.top",
    title: "Summaya & Anwaruddin — Wedding Invitation",
    description:
      "Celebrate the wedding of Summaya Ashraf & Anwaruddin Sheik on 1 & 3 Oct 2026 at Sri Siri Convention & Lions Auditorium. Hosted by Baji & Jareena Sheik.",
    ogTitle: "Summaya & Anwaruddin — Wedding Invitation",
    ogDescription:
      "Join Baji & Jareena Sheik in celebrating the wedding of their only son Anwaruddin with Summaya on 1 & 3 Oct 2026.",
    ogImage: "https://anwaruddin-weds-summaya.invitingyou.top/og-image.jpg",
    ogImageAlt: "Summaya & Anwaruddin Wedding Invitation",
    ogImageType: "image/jpeg",
    ogImageWidth: "1200",
    ogImageHeight: "630",
    ogSiteName: "InviteStory",
  },
  gallery: [
    "/wedding/rings-holding.png",
    "/wedding/ring-ceremony-2.jpg",
    "/wedding/ring-ceremony-1.jpg",
    "/wedding/rings-bw.png",
  ],
  closing:
    "Your presence and heartfelt duas are the most precious blessings for our only son and beloved daughter-in-law. Come, share this blessed celebration with the Sheik & Ashraf families, insha'Allah.",
} as const;
